Tri sub
Hy-An/Adopt pull request #1
Opened 2021-02-23 23:54 UTC by Chewbacci

Se cambió esqueleto.
Se cambió formato de elementos en conjunto (style.scss) a elementos por separado e index.scss
Se agregaron assets

-

Próximas modificaciones: Integración Mixer
Agregado de 4 páginas más.
Emprolijado de Logo.

--
Se está viendo de realizar:

Alguna animación.
Poner marcos animados.
Agregar una canción de fondo.
Agregar caja de texto para ingresar datos de mascota para colocar en adopción.
Tomar datos cargados por usuario para poder mostrarlos en otra página (deseable).
---

2021-02-24 00:15 UTC, nathan-hyan requested changes
Some comments

2021-02-24 00:15 UTC, nathan-hyan commented on Assets/Font/Akaya_Telivigala/OFL.txt
> +Copyright 2015 The Akaya Telivigala Project Authors (https://github.com/vaishnavimurthy/Akaya-Telivigala)
You can delete this file

2021-02-24 00:15 UTC, nathan-hyan commented on index.html
>        <h1 class="Tittle">Adopt Me!</h1>
use camelCase for class names

2021-02-24 00:15 UTC, nathan-hyan commented on index.html
>      <div class="Description">
same here

2021-02-24 00:15 UTC, nathan-hyan commented on index.html
>      <div class="Menu-Nav">
same with this

2021-02-24 00:15 UTC, nathan-hyan commented on index.html
> +        <div class="Columna-Img">
another one

2021-02-24 00:15 UTC, nathan-hyan commented on index.html
> +        <div class="Columna-Img2">
xd

2021-02-24 00:15 UTC, nathan-hyan commented on styles/_body.scss
> +    margin: 20px 20px 20px 20px;
You can shorten this

`margin: 20px;`

2021-02-24 00:15 UTC, nathan-hyan commented on styles/_body.scss
> +    height: 200px;
go with width, or max-width or min width. Not all 3

Mainly it's just width used. same for height

2021-02-24 00:15 UTC, nathan-hyan commented on styles/_body.scss
> +    justify-content: center;
`justify-content` or `align-items` works only in flexbox. You have to use CSSGrid now

2021-02-24 00:15 UTC, nathan-hyan commented on styles/_body.scss
> +    max-width: 1fr;
the unit `fr` is only used for dividing repeating cssgrids columns / rows. replace this with `px`

2021-02-24 00:15 UTC, nathan-hyan commented on styles/_body.scss
> +  .imag {
Use descriptive names

2021-02-24 00:15 UTC, nathan-hyan commented on styles/_footer.scss
> +  justify-content: center;
Only in flexbox

2021-02-24 00:15 UTC, nathan-hyan commented on styles/_header.scss
> +    padding: 1fr 1fr 1fr 1fr;
fr is only used for CSSgrids columns / rows. replace this with px and it can also be shortened as `padding: 0px`

2021-02-24 00:15 UTC, nathan-hyan commented on styles/_header.scss
> +    color: lightblue;
Use only variables for colors

2021-02-24 00:15 UTC, nathan-hyan commented on styles/_header.scss
> +    justify-content: auto;
only in flexbox

2021-02-24 00:15 UTC, nathan-hyan commented on styles/_header.scss
> +    border-color: gold;
border can be shortened as

`border: SIZE STYLE COLOR`

2021-02-24 00:15 UTC, nathan-hyan commented on styles/_main.scss
> +    justify-content: center;
only in flexbox

2021-02-24 00:15 UTC, nathan-hyan commented on styles/_nav.scss
> +.nv {
use descriptive names

2021-02-24 00:15 UTC, nathan-hyan commented on styles/_nav.scss
> +    border-color: gold;
border can be shortened as

`border: SIZE STYLE COLOR`

2021-02-24 00:15 UTC, nathan-hyan commented on styles/_nav.scss
> +    align-content: center;
only in flexbox

2021-02-24 00:15 UTC, nathan-hyan commented on styles/_nav.scss
> +    padding: 1fr 1fr 1fr 1fr;
same thing with fr

2021-02-24 00:15 UTC, nathan-hyan commented on styles/_nav.scss
> +    color: rgb(5, 112, 112);
use only variables for color

2021-02-24 00:15 UTC, nathan-hyan commented on styles/_nav.scss
> +    color: rgb(5, 112, 112);
and hex values hahaa

2021-02-24 00:15 UTC, nathan-hyan commented on styles/_variables.scss
> +$UnderlineColor: rgb(123, 209, 123);
Use only hex values for colors

2021-02-24 00:15 UTC, nathan-hyan commented on styles/index.scss
> +  background-color: rgb(179, 230, 247);
use variables for colors

2021-02-24 00:15 UTC, nathan-hyan commented on styles/index.scss
> +  background-color: rgb(179, 230, 247);
variables for colors

2021-02-26 12:18 UTC, Chewbacci commented
Cambios realizados

2021-02-26 13:23 UTC, nathan-hyan requested changes
Some comments

2021-02-26 13:23 UTC, nathan-hyan commented on index.html
>        <h1 class="Tittle">Adopt Me!</h1>
camelCase, first letter in lowercase and every next with Capital Case

2021-02-26 13:23 UTC, nathan-hyan commented on styles/_variables.scss
> +$navColor: #057070;
Be consistent when naming variables

2021-02-26 15:24 UTC, Chewbacci commented
Corregidos comentarios

2021-02-26 15:25 UTC, nathan-hyan approved these changes
🥇

2021-02-26 15:27 UTC, merged